// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "c2a40bba-4a14-4571-bba2-a06c7669d779");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1620021382);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1620021502);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1620020972);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1620021142);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1620021022);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1620021262);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1620021053);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1620021622);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 2399);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1620020943);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c7002319-ff08-4348-892e-4b29c9ef4c69}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1620020973479");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1620022746479");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1620020949030");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1620042549030");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200107212822");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1620020994");
user_pref("browser.slowStartup.averageTime", 4701);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1620020993);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1620020947302");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "b9289a5566c049029e14bb86b2e3ba18");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Thu, 25 Feb 2021 01:53:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1620021383);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200107212822");
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"0cd9f51b-f24d-4387-84d6-39cdbab7e563\",\"formautofill@mozilla.org\":\"b0ac982a-153f-45a0-bd7e-6bba5d418c56\",\"screenshots@mozilla.org\":\"568f2880-87ba-4122-9a07-8c132cf454dc\",\"webcompat-reporter@mozilla.org\":\"2a924b6a-e1c5-4113-9dd4-f9b1d1421fda\",\"webcompat@mozilla.org\":\"542240a8-57ea-4d4f-9af9-518515ced6ae\",\"default-theme@mozilla.org\":\"9a5798d3-3474-4dff-8094-4e978af0be7d\",\"google@search.mozilla.org\":\"de43cafd-113d-41a7-94a2-2fc68cc0da83\",\"amazondotcom@search.mozilla.org\":\"8eea5892-96e2-4ade-9727-bddf32af0af5\",\"bing@search.mozilla.org\":\"33287b93-cf65-4fac-95df-c161fc7c0543\",\"ddg@search.mozilla.org\":\"1bd041ec-735f-43e7-b664-a44c3f077416\",\"ebay@search.mozilla.org\":\"c38418d3-719a-452e-96f6-5a8b176e5359\",\"twitter@search.mozilla.org\":\"4c25c29a-d16b-4781-9bbb-530eb66cd91d\",\"wikipedia@search.mozilla.org\":\"06543466-9cc7-4548-b10b-2277e4655a40\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1620021232);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1620021073);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200107212822");
user_pref("media.gmp-manager.lastCheck", 1620021073);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1620021232);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "378cd0fe-9e28-4e69-9fa6-7d3dc62934de");
user_pref("security.sandbox.plugin.tempDirSuffix", "641f28bb-cea0-4694-9011-f4eead22153c");
user_pref("services.blocklist.pinning.checked", 1620021080);
user_pref("services.settings.clock_skew_seconds", -1336);
user_pref("services.settings.last_etag", "\"1620006473869\"");
user_pref("services.settings.last_update_seconds", 1620022598);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1620021080);
user_pref("services.settings.main.cfr-fxa.last_check", 1620021080);
user_pref("services.settings.main.cfr.last_check", 1620021080);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1620021080);
user_pref("services.settings.main.hijack-blocklists.last_check", 1620021080);
user_pref("services.settings.main.language-dictionaries.last_check", 1620021080);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1620021080);
user_pref("services.settings.main.public-suffix-list.last_check", 1620021080);
user_pref("services.settings.main.sites-classification.last_check", 1620021080);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1620021080);
user_pref("services.settings.main.whats-new-panel.last_check", 1620021080);
user_pref("services.settings.security.onecrl.checked", 1620021080);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1620021232);
user_pref("toolkit.startup.last_success", 1620020992);
user_pref("toolkit.telemetry.cachedClientID", "11314554-ef93-459f-ae57-029222472b4c");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
